directories: 
  history_dir:  !join [/archive/$USER/, *FRE_STEM, /, *name, /, *platform, -, *target, /, history]
  pp_dir:       !join [/archive/$USER/, *FRE_STEM, /, *name, /, *platform, -, *target, /, pp]
  analysis_dir: !join [/nbhome/$USER/, *FRE_STEM, /, *name]
  ptmp_dir:     "/xtmp/$USER/ptmp"
  fre_analysis_home: "/home/fms/local/opt/fre-analysis/test"

postprocess:
  workflow:
    repository: "https://github.com/NOAA-GFDL/fre-workflows"
    version: "2026.01-alpha1"
  settings:
    history_segment:    "P1Y"
    site:               "ppan"
#    pp_chunks:
#    pp_start:
#    pp_stop:
#    pp_grid_spec:      
  switches: 
    do_timeavgs:        True
    clean_work:         True
    do_refinediag:      False
    do_atmos_plevel_masking: True
    do_preanalysis:     False
    do_analysis:        True
    do_analysis_only:   False
